name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Setup Node.js enviroment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x
    
    # Install dependencies
    - name: Install dependencies
      run: yarn
      
    # Exec build
    - name: Run build
      run: yarn build
    
    # Copy repo to Digital Ocean
    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist"
        target: "test"
    
    # Substituir o código existente na pasta "dist" pelo novo código
    # Exec yarn in Digital Ocean
    # Exec migrations
    # Restart node server

    
