name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Setup Node.js enviroment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x
    
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    # Install dependencies
    - name: Install dependencies
      run: yarn
      
    # Exec build
    - name: Run build
      run: yarn build
    
    # Copy repo to Digital Ocean
    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "~/goyaz-barber-app/goyaz-barber-backend"
    
    # Substituir o código existente na pasta "dist" pelo novo código
    # Exec yarn in Digital Ocean
    # Exec migrations
    # Restart node server

    
